version: '3'
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres

  Configuration-Service:
    image: javatechnology/configuration-service:0.0.1-SNAPSHOT
    ports:
      - 8888:8888
    networks:
      backend:
        aliases:
            - "configuration-service"
    depends_on:
      - keycloak

  Eureka-Service:
    image: javatechnology/eureka-service:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      backend:
        aliases:
            - "eureka-service"
    depends_on:
      - keycloak
  Gateway-Service:
    image: javatechnology/gateway-service:0.0.1-SNAPSHOT
    ports:
      - 5555:5555
    networks:
      backend:
        aliases:
            - "gateway-service"
    depends_on:
      - keycloak
      - Eureka-Service
  License-Service:
    image: javatechnology/licensing-service:0.0.1-SNAPSHOT
    ports:
      - 9191:9191
    networks:
      backend:
        aliases:
            - "license-service"

    depends_on:
      - keycloak
      - Configuration-Service
      - Eureka-Service
      - Gateway-Service
    environment:
      PROFILE: "dev"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://localhost:8888"
  Organization-Service:
    image: javatechnology/organization-service:0.0.1-SNAPSHOT
    ports:
      - 9292:9292
    networks:
      backend:
        aliases:
            - "organization-service"

    depends_on:
      - keycloak
      - Configuration-Service
      - Eureka-Service
      - Gateway-Service
    environment:
      PROFILE: "dev"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://localhost:8888"
networks:
  backend:
    driver: bridge


